version: '2'

services:
    tyk_redis:
        image: redis:3.2
        hostname: redis
        ports:
            - "6379:6379"
        networks:
            gateway:
                aliases:
                    - redis

    tyk_mongo:
        image: mongo:3.0
        command: ["mongod", "--smallfiles"]
        hostname: mongo
        ports:
            - "27017:27017"
        networks:
            gateway:
                aliases:
                    - mongo

    tyk_dashboard:
        image: tykio/tyk-dashboard:latest
        ports:
            - "3000:3000"
            - "5000:5000"
        volumes:
            - ./tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf
        networks:
            - gateway

    tyk_pump:
        image: tykio/tyk-pump-docker-pub:latest
        networks:
            - gateway
        volumes:
            - ./pump.conf:/opt/tyk-pump/pump.conf

    tyk_gateway:
        image: tykio/tyk-gateway:latest
        hostname: tyk-gateway
        ports:
            - "80:8080"
            - "8080:8080"
        volumes:
            - ./middleware:/opt/tyk-gateway-middleware
            - ./tyk.conf:/opt/tyk-gateway/tyk.conf
            - ./certs:/opt/tyk-gateway/certs
        networks:
            - gateway

    keycloak:
        image: jboss/keycloak:latest
        hostname: keycloak
        ports:
            - 38080:8080
        networks:
            - gateway
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin123

    haproxy:
        image: haproxy:alpine
        ports:
            - 38081:80
        volumes:
            - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
        networks:
            - gateway

    nginx:
        image: nginx:latest
        ports:
            - 38082:80
        volumes:
            - ./nginx:/usr/share/nginx/html:ro
        networks:
            - gateway

    grpc:
        image: tyk-auth-golang-grpc-plugin:1.0
        ports:
            - 35000:5000
        networks:
            - gateway

    simple-api:
        image: nextmetaphor/simple-golang-api:latest
        hostname: simple-golang-api
        ports:
            - 28080:8080
        networks:
            - gateway

    gatling:
        image: nextmetaphor/alpine-gatling
        entrypoint: ["tail", "-f", "/dev/null"]
        networks:
            - gateway
        volumes:
            - ./gatling/conf:/opt/gatling-charts-highcharts-bundle-2.2.5/conf
            - ./gatling/user-files:/opt/gatling-charts-highcharts-bundle-2.2.5/user-files
            - ./gatling/results:/opt/gatling-charts-highcharts-bundle-2.2.5/results

networks:
    gateway: